('리오넬_메시',
'{"speed": 85, "finishing": 95, "shot_power": 95, "defense": 40, "stamina": 60}',
'SuperRare',
NOW(),
NOW()),
  ('크리스티아누_호날두',
  '{"speed": 90, "finishing": 94, "shot_power": 94, "defense": 45, "stamina": 80}',
  'SuperRare',
  NOW(),
  NOW()),
  ('네이마르',
  '{"speed": 87, "finishing": 91, "shot_power": 91, "defense": 45, "stamina": 65}',
  'SuperRare',
  NOW(),
  NOW()),
  ('킬리안_음바페',
  '{"speed": 96, "finishing": 89, "shot_power": 89, "defense": 40, "stamina": 70}',
  'SuperRare',
  NOW(),
  NOW()),
  ('로베르토_레반도프스키',
  '{"speed": 75, "finishing": 93, "shot_power": 93, "defense": 60, "stamina": 80}',
  'Rare',
  NOW(),
  NOW()),
  ('에르링_홀란드',
  '{"speed": 92, "finishing": 92, "shot_power": 92, "defense": 50, "stamina": 85}',
  'SuperRare',
  NOW(),
  NOW()),
  ('모하메드_살라',
  '{"speed": 90, "finishing": 89, "shot_power": 89, "defense": 40, "stamina": 65}',
  'Rare',
  NOW(),
  NOW()),
  ('케빈_데_브라위너',
  '{"speed": 75, "finishing": 85, "shot_power": 85, "defense": 60, "stamina": 75}',
  'SuperRare',
  NOW(),
  NOW()),
  ('루카_모드리치',
  '{"speed": 75, "finishing": 85, "shot_power": 85, "defense": 50, "stamina": 70}',
  'Rare',
  NOW(),
  NOW()),
  ('토니_크로스',
  '{"speed": 70, "finishing": 80, "shot_power": 80, "defense": 50, "stamina": 70}',
  'Rare',
  NOW(),
  NOW()),
  ('파울로_디발라',
  '{"speed": 85, "finishing": 88, "shot_power": 88, "defense": 40, "stamina": 60}',
  'Rare',
  NOW(),
  NOW()),
  ('하리_케인',
  '{"speed": 80, "finishing": 92, "shot_power": 92, "defense": 55, "stamina": 75}',
  'Rare',
  NOW(),
  NOW()),
  ('필리페_쿠티뉴',
  '{"speed": 85, "finishing": 85, "shot_power": 85, "defense": 40, "stamina": 60}',
  'Rare',
  NOW(),
  NOW()),
  ('브루노_페르난데스',
  '{"speed": 75, "finishing": 84, "shot_power": 84, "defense": 55, "stamina": 70}',
  'Rare',
  NOW(),
  NOW()),
  ('주드_벨링햄',
  '{"speed": 80, "finishing": 85, "shot_power": 85, "defense": 60, "stamina": 80}',
  'Rare',
  NOW(),
  NOW()),
  ('잉그레스',
  '{"speed": 70, "finishing": 80, "shot_power": 80, "defense": 55, "stamina": 75}',
  'Common',
  NOW(),
  NOW()),
  ('앙투안_그리즈만',
  '{"speed": 85, "finishing": 88, "shot_power": 88, "defense": 45, "stamina": 60}',
  'Rare',
  NOW(),
  NOW()),
  ('수아레스',
  '{"speed": 75, "finishing": 90, "shot_power": 90, "defense": 55, "stamina": 85}',
  'Rare',
  NOW(),
  NOW()),
  ('손흥민',
  '{"speed": 94, "finishing": 90, "shot_power": 90, "defense": 52, "stamina": 95}',
  'SuperRare',
  NOW(),
  NOW()),
  ('마르코_로이스',
  '{"speed": 85, "finishing": 87, "shot_power": 87, "defense": 50, "stamina": 70}',
  'Rare',
  NOW(),
  NOW()),
  ('카림_벤제마',
  '{"speed": 80, "finishing": 90, "shot_power": 90, "defense": 50, "stamina": 75}',
  'Rare',
  NOW(),
  NOW()),
  ('일카이_귄도안',
  '{"speed": 75, "finishing": 80, "shot_power": 80, "defense": 60, "stamina": 75}',
  'Common',
  NOW(),
  NOW()),
  ('조르지뉴',
  '{"speed": 70, "finishing": 75, "shot_power": 75, "defense": 60, "stamina": 70}',
  'Common',
  NOW(),
  NOW()),
  ('진-리_카잔',
  '{"speed": 70, "finishing": 80, "shot_power": 80, "defense": 55, "stamina": 75}',
  'Common',
  NOW(),
  NOW()),
  ('레오나르도_보누치',
  '{"speed": 70, "finishing": 50, "shot_power": 50, "defense": 90, "stamina": 85}',
  'Rare',
  NOW(),
  NOW()),
  ('루카스_헤르난데스',
  '{"speed": 80, "finishing": 55, "shot_power": 55, "defense": 90, "stamina": 85}',
  'Rare',
  NOW(),
  NOW()),
  ('마르코_아센시오',
  '{"speed": 80, "finishing": 85, "shot_power": 85, "defense": 50, "stamina": 70}',
  'Rare',
  NOW(),
  NOW())(
    '로날드_쿠만',
    '{"speed": 70, "finishing": 80, "shot_power": 85, "defense": 80, "stamina": 70}',
    'Rare',
    NOW(),
    NOW(),
  ),
  ('디에고_마라도나',
  '{"speed": 80, "finishing": 95, "shot_power": 90, "defense": 50, "stamina": 70}',
  'SuperRare',
  NOW(),
  NOW()),
  ('지네딘_지단',
  '{"speed": 75, "finishing": 85, "shot_power": 85, "defense": 70, "stamina": 75}',
  'SuperRare',
  NOW(),
  NOW()),
  ('세르히오_라모스',
  '{"speed": 75, "finishing": 60, "shot_power": 75, "defense": 95, "stamina": 85}',
  'Rare',
  NOW(),
  NOW()),
  ('파트리크_비에이라',
  '{"speed": 80, "finishing": 80, "shot_power": 80, "defense": 90, "stamina": 85}',
  'Rare',
  NOW(),
  NOW()),
  ('프랭크_램파드',
  '{"speed": 70, "finishing": 88, "shot_power": 90, "defense": 60, "stamina": 80}',
  'Rare',
  NOW(),
  NOW()),
  ('로베르토_카를로스',
  '{"speed": 90, "finishing": 80, "shot_power": 95, "defense": 80, "stamina": 85}',
  'SuperRare',
  NOW(),
  NOW()),
  ('파울로_말디니',
  '{"speed": 70, "finishing": 50, "shot_power": 60, "defense": 95, "stamina": 80}',
  'SuperRare',
  NOW(),
  NOW()),
  ('호베르토_필리포',
  '{"speed": 80, "finishing": 75, "shot_power": 80, "defense": 85, "stamina": 75}',
  'Rare',
  NOW(),
  NOW()),
  ('알렉스_산드로',
  '{"speed": 85, "finishing": 60, "shot_power": 75, "defense": 85, "stamina": 80}',
  'Rare',
  NOW(),
  NOW()),
  ('사미르_한도비치',
  '{"speed": 70, "finishing": 50, "shot_power": 60, "defense": 80, "stamina": 85}',
  'Common',
  NOW(),
  NOW()),
  ('티에리_앙리',
  '{"speed": 90, "finishing": 90, "shot_power": 85, "defense": 50, "stamina": 75}',
  'SuperRare',
  NOW(),
  NOW()),
  ('앙헬_디_마리아',
  '{"speed": 85, "finishing": 85, "shot_power": 85, "defense": 45, "stamina": 80}',
  'Rare',
  NOW(),
  NOW()),
  ('마르셀로',
  '{"speed": 85, "finishing": 70, "shot_power": 80, "defense": 75, "stamina": 85}',
  'Rare',
  NOW(),
  NOW()),
  ('아이비_알렌',
  '{"speed": 70, "finishing": 60, "shot_power": 70, "defense": 75, "stamina": 75}',
  'Common',
  NOW(),
  NOW()),
  ('하비에르_마르티네스',
  '{"speed": 70, "finishing": 50, "shot_power": 65, "defense": 85, "stamina": 80}',
  'Rare',
  NOW(),
  NOW()),
  ('디디에_드로그바',
  '{"speed": 80, "finishing": 90, "shot_power": 95, "defense": 50, "stamina": 80}',
  'SuperRare',
  NOW(),
  NOW()),
  ('페르난도_토레스',
  '{"speed": 85, "finishing": 88, "shot_power": 85, "defense": 50, "stamina": 75}',
  'Rare',
  NOW(),
  NOW()),
  ('카카',
  '{"speed": 90, "finishing": 92, "shot_power": 90, "defense": 50, "stamina": 80}',
  'SuperRare',
  NOW(),
  NOW()),
  ('마이클_캐릭',
  '{"speed": 75, "finishing": 75, "shot_power": 80, "defense": 80, "stamina": 85}',
  'Rare',
  NOW(),
  NOW())(
    '이강인',
    '{"speed": 85, "finishing": 85, "shot_power": 80, "defense": 50, "stamina": 75}',
    'Rare',
    NOW(),
    NOW(),
  ),
  ('정우영',
  '{"speed": 80, "finishing": 75, "shot_power": 80, "defense": 60, "stamina": 80}',
  'Rare',
  NOW(),
  NOW()),
  ('김민재',
  '{"speed": 80, "finishing": 50, "shot_power": 60, "defense": 90, "stamina": 85}',
  'Rare',
  NOW(),
  NOW()),
  ('황의조',
  '{"speed": 85, "finishing": 85, "shot_power": 85, "defense": 55, "stamina": 80}',
  'Rare',
  NOW(),
  NOW()),
  ('손준호',
  '{"speed": 75, "finishing": 70, "shot_power": 75, "defense": 80, "stamina": 80}',
  'Common',
  NOW(),
  NOW())(
    '차두리',
    '{"speed": 85, "finishing": 60, "shot_power": 65, "defense": 85, "stamina": 85}',
    'Rare',
    NOW(),
    NOW(),
  )(
    '박지성',
    '{"speed": 80, "finishing": 75, "shot_power": 75, "defense": 80, "stamina": 90}',
    'SuperRare',
    NOW(),
    NOW(),
  );
