[
  {
    name: "리오넬_메시",
    position: "ST",
    shoot: 95,
    pass: 88,
    dribble: 96,
    defense: 40,
    stamina: 60,
    speed: 85,
    rarity: "SuperRare",
  },
  {
    name: "크리스티아누_호날두",
    position: "ST",
    shoot: 94,
    pass: 80,
    dribble: 85,
    defense: 45,
    stamina: 80,
    speed: 90,
    rarity: "SuperRare",
  },
  {
    name: "네이마르",
    position: "ST",
    shoot: 91,
    pass: 85,
    dribble: 94,
    defense: 45,
    stamina: 65,
    speed: 87,
    rarity: "SuperRare",
  },
  {
    name: "킬리안_음바페",
    position: "ST",
    shoot: 89,
    pass: 78,
    dribble: 93,
    defense: 40,
    stamina: 70,
    speed: 96,
    rarity: "SuperRare",
  },
  {
    name: "로베르토_레반도프스키",
    position: "ST",
    shoot: 93,
    pass: 80,
    dribble: 85,
    defense: 60,
    stamina: 80,
    speed: 75,
    rarity: "Rare",
  },
  {
    name: "에르링_홀란드",
    position: "ST",
    shoot: 92,
    pass: 75,
    dribble: 80,
    defense: 50,
    stamina: 85,
    speed: 92,
    rarity: "SuperRare",
  },
  {
    name: "모하메드_살라",
    position: "ST",
    shoot: 89,
    pass: 80,
    dribble: 88,
    defense: 40,
    stamina: 65,
    speed: 90,
    rarity: "Rare",
  },
  {
    name: "케빈_데_브라위너",
    position: "MF",
    shoot: 85,
    pass: 94,
    dribble: 89,
    defense: 60,
    stamina: 75,
    speed: 75,
    rarity: "SuperRare",
  },
  {
    name: "루카_모드리치",
    position: "MF",
    shoot: 85,
    pass: 93,
    dribble: 90,
    defense: 50,
    stamina: 70,
    speed: 75,
    rarity: "Rare",
  },
  {
    name: "토니_크로스",
    position: "MF",
    shoot: 80,
    pass: 93,
    dribble: 85,
    defense: 50,
    stamina: 70,
    speed: 70,
    rarity: "Rare",
  },
  {
    name: "파울로_디발라",
    position: "ST",
    shoot: 88,
    pass: 85,
    dribble: 90,
    defense: 40,
    stamina: 60,
    speed: 85,
    rarity: "Rare",
  },
  {
    name: "하리_케인",
    position: "ST",
    shoot: 92,
    pass: 80,
    dribble: 83,
    defense: 55,
    stamina: 75,
    speed: 80,
    rarity: "Rare",
  },
  {
    name: "필리페_쿠티뉴",
    position: "MF",
    shoot: 85,
    pass: 88,
    dribble: 91,
    defense: 40,
    stamina: 60,
    speed: 85,
    rarity: "Rare",
  },
  {
    name: "브루노_페르난데스",
    position: "MF",
    shoot: 84,
    pass: 91,
    dribble: 90,
    defense: 55,
    stamina: 70,
    speed: 75,
    rarity: "Rare",
  },
  {
    name: "주드_벨링햄",
    position: "MF",
    shoot: 85,
    pass: 86,
    dribble: 88,
    defense: 60,
    stamina: 80,
    speed: 80,
    rarity: "Rare",
  },
  {
    name: "잉그레스",
    position: "MF",
    shoot: 80,
    pass: 88,
    dribble: 85,
    defense: 55,
    stamina: 75,
    speed: 70,
    rarity: "Common",
  },
  {
    name: "앙투안_그리즈만",
    position: "ST",
    shoot: 88,
    pass: 85,
    dribble: 88,
    defense: 45,
    stamina: 60,
    speed: 85,
    rarity: "Rare",
  },
  {
    name: "수아레스",
    position: "ST",
    shoot: 90,
    pass: 80,
    dribble: 80,
    defense: 55,
    stamina: 85,
    speed: 75,
    rarity: "Rare",
  },
  {
    name: "손흥민",
    position: "ST",
    shoot: 90,
    pass: 96,
    dribble: 89,
    defense: 52,
    stamina: 95,
    speed: 94,
    rarity: "SuperRare",
  },
  {
    name: "마르코_로이스",
    position: "ST",
    shoot: 87,
    pass: 80,
    dribble: 90,
    defense: 50,
    stamina: 70,
    speed: 85,
    rarity: "Rare",
  },
  {
    name: "카림_벤제마",
    position: "ST",
    shoot: 90,
    pass: 80,
    dribble: 85,
    defense: 50,
    stamina: 75,
    speed: 80,
    rarity: "Rare",
  },
  {
    name: "일카이_귄도안",
    position: "MF",
    shoot: 80,
    pass: 87,
    dribble: 85,
    defense: 60,
    stamina: 75,
    speed: 75,
    rarity: "Common",
  },
  {
    name: "조르지뉴",
    position: "MF",
    shoot: 75,
    pass: 90,
    dribble: 80,
    defense: 60,
    stamina: 70,
    speed: 70,
    rarity: "Common",
  },
  {
    name: "진-리_카잔",
    position: "MF",
    shoot: 80,
    pass: 85,
    dribble: 80,
    defense: 55,
    stamina: 75,
    speed: 70,
    rarity: "Common",
  },
  {
    name: "레오나르도_보누치",
    position: "D",
    shoot: 50,
    pass: 60,
    dribble: 55,
    defense: 90,
    stamina: 85,
    speed: 70,
    rarity: "Rare",
  },
  {
    name: "루카스_헤르난데스",
    position: "D",
    shoot: 55,
    pass: 60,
    dribble: 60,
    defense: 90,
    stamina: 85,
    speed: 80,
    rarity: "Rare",
  },
  {
    name: "마르코_아센시오",
    position: "ST",
    shoot: 85,
    pass: 82,
    dribble: 90,
    defense: 50,
    stamina: 70,
    speed: 80,
    rarity: "Rare",
  },
];
